### ISSUE TITLE
Music will sometimes not play and get stuck in queue

### ISSUE THREAD

**Issue by squigjess** [squigjess/JukeBot#1]
**Issue:** Playing a track will occasionally result in an AttributeError, causing music to not be played

**Reproduction:** Play a track with the `play` command. It may or may not occur.

**Error log:**

```
Ignoring exception in command play:
Traceback (most recent call last):
  File "/home/jess/Projects/JukeBot/venv/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jess/Projects/JukeBot/music_player.py", line 96, in play
    await self.play_music()
  File "/home/jess/Projects/JukeBot/music_player.py", line 68, in play_music
    self.vc = await self.client.move_to(self.music_queue[0][1])
AttributeError: 'Bot' object has no attribute 'move_to'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/jess/Projects/JukeBot/venv/lib/python3.9/site-packages/nextcord/ext/commands/bot.py", line 995, in invoke
    await ctx.command.invoke(ctx)
  File "/home/jess/Projects/JukeBot/venv/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 895, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/jess/Projects/JukeBot/venv/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 177, in wrapped
    raise CommandInvokeError(exc) from exc
nextcord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Bot' object has no attribute 'move_to'

```

**Comment by squigjess** [comment]
idk how i fixed it but i did lmfao
