### ISSUE TITLE
!nowplaying occasionally fails to subtract times

### ISSUE THREAD

**Issue by squigjess** [squigjess/JukeBot#13]
```
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "/home/jess/Projects/JukeBot/JukeBot-Proj/venv/lib/python3.9/site-packages/nextcord/ext/commands/core.py", line 168, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/jess/Projects/JukeBot/JukeBot-Proj/JukeBot/audio_commands.py", line 328, in nowplaying
    reply.add_field(name="Time remaining", value=currently_playing.time_left(arrow.utcnow()), inline=True)
  File "/home/jess/Projects/JukeBot/JukeBot-Proj/JukeBot/data.py", line 31, in time_left
    diff = time_now - self.time_started
TypeError: unsupported operand type(s) for -: 'Arrow' and 'NoneType'

```

**Comment by squigjess** [comment]
Looks like this issue occurs when trying to call `!nowplaying` before the track has actually started playing, which is a weird edge case. Will keep an eye on this to see whether the above commit fixes it or not.

**Comment by squigjess** [comment]
This appears to be caused by the fact that only the first track in a queue gets its start time recorded. Fixed below.

https://github.com/squigjess/JukeBot/blob/9d13c9f96c4118cf0be0a125c9ad7992728ecde7/JukeBot/audio_commands.py#L161
